### ISSUE TITLE
[prod] ActionView::Template::Error in quick_search/search # xhr_search

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul-bento-app#97]
`ActionView::Template::Error: undefined local variable or method 'searcher' for #<#<Class:0x000000031d5080>:0x007f5c50ca8308> Did you mean? search_field`

```
_module_heading.html.erb  9  _app_views_quick_search_search__module_heading_html_erb(...)
--
```

See https://app.honeybadger.io/projects/53517/faults/34759021

**Comment by camillevilla** [comment]
Er...I wonder if this was introduced by #92. I'll check it out.
